# -*- coding: utf-8 -*-
"""Exampractice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zu9CbDUmRt6DzhThq2xIVo-JW9ADywna
"""

!pip install pandas
df=pd.read_csv('Course Evaluation_Parami.csv')
print(df)

import pandas as pd
df=pd.read_csv('Course Evaluation_Parami.csv')
a = {'Strongly agree': 6, 'Agree': 4, 'Neutral': 1}
print('Agree students =',a['Agree'])
df=pd.DataFrame(dict.items(a))
print(df)

"""#Write Python codes read your survey data 'Course Evaluation_Parami.csv'# and compute to print the average age for each gender type.# draw boxplot to demonstrate the age distribution of th students.

"""

import pandas as pd
df=pd.read_csv('Course Evaluation_Parami.csv')
print(df.groupby ('Gender')['Age'].mean())


import matplotlib.pyplot as plt 
female = df[df['Gender']=='Female']
male = df[df['Gender']=='Male']
plt.boxplot([female['Age'], male['Age']], labels = ['female', 'male'])
plt.show()

